default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

development:
  <<: *default
  host: <%= ENV.fetch("DB_HOSTNAME", "localhost") %>
  database: <%= ENV.fetch("DB_NAME", "fuse_dev") %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

test:
  <<: *default
  host: <%= ENV.fetch("DB_HOSTNAME", "localhost") %>
  database: <%= ENV.fetch("DB_NAME_TEST", "fuse_test") %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
